server:
  port: 3002
spring:
  application:
    name: email-service
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bridgeflow}
    username: ${POSTGRES_USER:bridgeflow}
    password: ${POSTGRES_PASSWORD:bridgeflow123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  mq:
    exchange: bridgeflow.exchange
    queue: email.outbox
    routing:
      operacao_created: bridgeflow.routingkey
  mail:
    from: ${MAIL_FROM:no-reply@monitor-ellas.local}
